# Generated by Django 3.2.8 on 2022-02-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_auto_20220219_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcourses',
            name='started_from',
            field=models.DateTimeField(verbose_name='Started From'),
        ),
    ]
