# Generated by Django 3.2.8 on 2022-02-19 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_alter_allcourses_started_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allcourses',
            name='started_from',
        ),
    ]
