# Generated by Django 3.2.8 on 2022-02-19 07:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_remove_allcourses_started_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcourses',
            name='started_from',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Started From'),
            preserve_default=False,
        ),
    ]
